#!/bin/bash
# Here do anything needed to install the service
# i.e. apt-get install -y foo  or  bzr branch http://myserver/mycode /srv/webroot
# Make sure this hook exits cleanly and is idempotent, common problems here are
# failing to account for a debconf question on a dependency, or trying to pull
# from github without installing git first.

apt-get install -y apache2 libapache2-mod-python patch subversion python-svn python-setuptools python-mysqldb python-memcache libapache2-mod-wsgi python-imaging python-psycopg2

#PostgreSQL python client
#easy_install psycopg2

a2enmod python

easy_install FeedParser==5.1.2
easy_install reviewboard

cat << EOF > settings.sh
dbtype=sqlite3
dbname=/var/www/reviewboard/data/reviewboard.db
cachetype=file
cacheinfo=/tmp/reviewboard_cache
EOF

source ${CHARM_DIR}/hooks/rb-site-install

