#!/bin/bash

source settings.sh

sitename=`unit-get public-address`
sitedir=/var/www/reviewboard
webserver=apache
pythonloader=wsgi
adminuser=`config-get admin-username`
adminpass=`config-get admin-password`

if [ -e $sitedir ]; then
   juju-log "Removing old site files"
   rm -fR $sitedir
fi

if [ $dbtype = "sqlite3" ]; then
	rb-site install --noinput \
	     --domain-name=$sitename \
	     --site-root=/ \
	     --db-type=$dbtype \
	     --db-name=$dbname \
	     --web-server-type=$webserver \
	     --python-loader=$pythonloader \
	     --cache-type=$cachetype \
	     --cache-info=$cacheinfo \
	     --admin-user=$adminuser \
	     --admin-password=$adminpass \
	     $sitedir
else
	rb-site install --noinput \
	     --domain-name=$sitename \
	     --site-root=/ \
	     --db-type=$dbtype \
	     --db-host=$dbhost \
	     --db-name=$dbname \
	     --db-user=$dbuser \
	     --db-pass=$dbpassword \
	     --web-server-type=$webserver \
	     --python-loader=$pythonloader \
	     --cache-type=$cachetype \
	     --cache-info=$cacheinfo \
	     --admin-user=$adminuser \
	     --admin-password=$adminpass \
	     $sitedir
fi

chown www-data:www-data -R /var/www/reviewboard/htdocs/media/uploaded/
chown www-data:www-data -R /var/www/reviewboard/htdocs/media/ext/
#looks like we need to enable this dir in any case
#if [ $dbtype = "sqlite3" ]; then
chown www-data:www-data -R /var/www/reviewboard/data/
#fi

cp /var/www/reviewboard/conf/apache-wsgi.conf /etc/apache2/sites-enabled/reviewboard

a2dissite default
a2ensite reviewboard

service apache2 restart
